[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200